#!/bin/bash

REPOURL=`git remote -v | grep "fetch" | grep "origin" | cut -d "@" -f2 | cut -d " " -f1 | cut -d "." -f1,2 | tr : /`
if [ ! -z "$REPOURL" ]; then
    echo $REPOURL
    explorer.exe https://$REPOURL
fi
