#!/usr/bin/env bash

#     for arg in "$@"
# function parse_with_for_in() {
#     do
#         echo $arg
#     done
# }
# function parse_with_expansion() {
#     for ((i = 1; i <= $#; i++))
#     do
#         echo ${i} # Indirect expansion syntax
#     done
# }
# parse_with_for_in "$@"
# echo "---"
# parse_with_expansion "$@"
# echo "filename" $0


# while [ ! $# -eq 0 ]
# do
# 	case "$1" in
# 		--help | -h)
# 			echo "help"
# 			exit
# 			;;
# 		--take-over-world | -t)
# 			echo "secretopt"
# 			exit
# 			;;
#     --test)
#       echo "test"
#       exit
#       ;;
# 	esac
# 	shift
# done


while getopts 'lha:' OPTION; do
  case "$OPTION" in
    l)
      echo "linuxconfig"
      ;;
    h)
      echo "you have supplied the -h option"
      ;;
    a)
      avalue="$OPTARG"
      echo "The value provided is $OPTARG"
      ;;
    ?)
      echo "script usage: $(basename \$0) [-l] [-h] [-a somevalue]" >&2
      exit 1
      ;;
  esac
done
shift "$(($OPTIND -1))"
